// <auto-generated />
using System;
using CSDLPT_API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSDLPT_API.Entities
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSDLPT_API.Entities.BienLai", b =>
                {
                    b.Property<string>("MaLop")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maLop");

                    b.Property<string>("MaSv")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maSV");

                    b.Property<long>("Nam")
                        .HasColumnType("bigint")
                        .HasColumnName("nam");

                    b.Property<Guid>("Rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rowguid")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<long?>("SoBienLai")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 5)")
                        .HasColumnName("soTien");

                    b.Property<long>("Thang")
                        .HasColumnType("bigint")
                        .HasColumnName("thang");

                    b.HasKey("MaLop", "MaSv")
                        .HasName("bienlai_malop_sv_primary");

                    b.HasIndex("MaSv");

                    b.HasIndex(new[] { "Rowguid" }, "MSmerge_index_1029578706")
                        .IsUnique();

                    b.HasIndex(new[] { "SoBienLai" }, "bienlai_sobienlai_unique")
                        .IsUnique()
                        .HasFilter("[SoBienLai] IS NOT NULL");

                    b.ToTable("BienLai", null, t =>
                        {
                            t.HasTrigger("MSmerge_del_2B4D61663ED5437485DA13BF01E2A094");

                            t.HasTrigger("MSmerge_ins_2B4D61663ED5437485DA13BF01E2A094");

                            t.HasTrigger("MSmerge_upd_2B4D61663ED5437485DA13BF01E2A094");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CSDLPT_API.Entities.CauLacBo", b =>
                {
                    b.Property<string>("MaClb")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maCLB");

                    b.Property<Guid>("Rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rowguid")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("TenClb")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenCLB");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenKhoa");

                    b.HasKey("MaClb")
                        .HasName("cau_lac_bo_maclb_primary");

                    b.HasIndex(new[] { "Rowguid" }, "MSmerge_index_901578250")
                        .IsUnique();

                    b.ToTable("Cau_Lac_Bo", null, t =>
                        {
                            t.HasTrigger("MSmerge_del_8090A7E0E09A4934B1C4A47D77456749");

                            t.HasTrigger("MSmerge_ins_8090A7E0E09A4934B1C4A47D77456749");

                            t.HasTrigger("MSmerge_upd_8090A7E0E09A4934B1C4A47D77456749");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CSDLPT_API.Entities.GiangVien", b =>
                {
                    b.Property<string>("MaGv")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maGV");

                    b.Property<string>("HoTenGv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hoTenGV");

                    b.Property<string>("MaClb")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maCLB");

                    b.Property<Guid>("Rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rowguid")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.HasKey("MaGv")
                        .HasName("giang_vien_magv_primary");

                    b.HasIndex("MaClb");

                    b.HasIndex(new[] { "Rowguid" }, "MSmerge_index_933578364")
                        .IsUnique();

                    b.ToTable("Giang_Vien", null, t =>
                        {
                            t.HasTrigger("MSmerge_del_BBE491BE857B46C1A1B3972E16EFA82F");

                            t.HasTrigger("MSmerge_ins_BBE491BE857B46C1A1B3972E16EFA82F");

                            t.HasTrigger("MSmerge_upd_BBE491BE857B46C1A1B3972E16EFA82F");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CSDLPT_API.Entities.LopNangKhieu", b =>
                {
                    b.Property<string>("MaLop")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maLop");

                    b.Property<long>("HocPhi")
                        .HasColumnType("bigint")
                        .HasColumnName("hocPhi");

                    b.Property<string>("MaGv")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maGV");

                    b.Property<DateTime>("NgayMo")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayMo");

                    b.Property<Guid>("Rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rowguid")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.HasKey("MaLop")
                        .HasName("lopnangkhieu_malop_primary");

                    b.HasIndex("MaGv");

                    b.HasIndex(new[] { "Rowguid" }, "MSmerge_index_997578592")
                        .IsUnique();

                    b.ToTable("LopNangKhieu", null, t =>
                        {
                            t.HasTrigger("MSmerge_del_C310E0F273B1411B9D3E7C509BC7FC97");

                            t.HasTrigger("MSmerge_ins_C310E0F273B1411B9D3E7C509BC7FC97");

                            t.HasTrigger("MSmerge_upd_C310E0F273B1411B9D3E7C509BC7FC97");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CSDLPT_API.Entities.Sinhvien", b =>
                {
                    b.Property<string>("MaSv")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maSV");

                    b.Property<string>("MaClb")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maCLB");

                    b.Property<Guid>("Rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rowguid")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("TenSv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenSV");

                    b.HasKey("MaSv")
                        .HasName("sinhvien_masv_primary");

                    b.HasIndex("MaClb");

                    b.HasIndex(new[] { "Rowguid" }, "MSmerge_index_965578478")
                        .IsUnique();

                    b.ToTable("Sinhvien", null, t =>
                        {
                            t.HasTrigger("MSmerge_del_A5F875CD00564922B0F0411FB1DFD078");

                            t.HasTrigger("MSmerge_ins_A5F875CD00564922B0F0411FB1DFD078");

                            t.HasTrigger("MSmerge_upd_A5F875CD00564922B0F0411FB1DFD078");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CSDLPT_API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CSDLPT_API.Entities.BienLai", b =>
                {
                    b.HasOne("CSDLPT_API.Entities.LopNangKhieu", "MaLopNavigation")
                        .WithMany("BienLais")
                        .HasForeignKey("MaLop")
                        .IsRequired()
                        .HasConstraintName("bienlai_malop_foreign");

                    b.HasOne("CSDLPT_API.Entities.Sinhvien", "MaSvNavigation")
                        .WithMany("BienLais")
                        .HasForeignKey("MaSv")
                        .IsRequired()
                        .HasConstraintName("bienlai_masv_foreign");

                    b.Navigation("MaLopNavigation");

                    b.Navigation("MaSvNavigation");
                });

            modelBuilder.Entity("CSDLPT_API.Entities.GiangVien", b =>
                {
                    b.HasOne("CSDLPT_API.Entities.CauLacBo", "MaClbNavigation")
                        .WithMany("GiangViens")
                        .HasForeignKey("MaClb")
                        .IsRequired()
                        .HasConstraintName("giang_vien_maclb_foreign");

                    b.Navigation("MaClbNavigation");
                });

            modelBuilder.Entity("CSDLPT_API.Entities.LopNangKhieu", b =>
                {
                    b.HasOne("CSDLPT_API.Entities.GiangVien", "MaGvNavigation")
                        .WithMany("LopNangKhieus")
                        .HasForeignKey("MaGv")
                        .IsRequired()
                        .HasConstraintName("lopnangkhieu_magv_foreign");

                    b.Navigation("MaGvNavigation");
                });

            modelBuilder.Entity("CSDLPT_API.Entities.Sinhvien", b =>
                {
                    b.HasOne("CSDLPT_API.Entities.CauLacBo", "MaClbNavigation")
                        .WithMany("Sinhviens")
                        .HasForeignKey("MaClb")
                        .IsRequired()
                        .HasConstraintName("sinhvien_maclb_foreign");

                    b.Navigation("MaClbNavigation");
                });

            modelBuilder.Entity("CSDLPT_API.Entities.CauLacBo", b =>
                {
                    b.Navigation("GiangViens");

                    b.Navigation("Sinhviens");
                });

            modelBuilder.Entity("CSDLPT_API.Entities.GiangVien", b =>
                {
                    b.Navigation("LopNangKhieus");
                });

            modelBuilder.Entity("CSDLPT_API.Entities.LopNangKhieu", b =>
                {
                    b.Navigation("BienLais");
                });

            modelBuilder.Entity("CSDLPT_API.Entities.Sinhvien", b =>
                {
                    b.Navigation("BienLais");
                });
#pragma warning restore 612, 618
        }
    }
}
