// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.dbConnection;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(threaterManagementDbContext))]
    [Migration("20250923161756_add-customerInfo_table")]
    partial class addcustomerInfo_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.model.customerModel", b =>
                {
                    b.Property<string>("customerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("identityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("customerId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("customerModel");
                });

            modelBuilder.Entity("backend.model.roleModel", b =>
                {
                    b.Property<string>("roleId")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("roleName")
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("roleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            roleId = "6ae7fd25-7abc-4886-b3d2-7a6bffbbb62b",
                            roleName = "Director"
                        },
                        new
                        {
                            roleId = "b6bc151a-b4b4-41d6-bae4-62ce5627be2f",
                            roleName = "Customer"
                        },
                        new
                        {
                            roleId = "efcddae9-75cf-40e0-be76-8226ea26664e",
                            roleName = "Threater Manager"
                        },
                        new
                        {
                            roleId = "fe4b6c29-b60f-4ea4-a2b8-4b9d6a1c2300",
                            roleName = "System Manager"
                        },
                        new
                        {
                            roleId = "77fa1f11-3481-451a-8eba-2586d519f56d",
                            roleName = "Movie Manager"
                        },
                        new
                        {
                            roleId = "e6380167-8440-4762-b386-3cfa5f0ac9fa",
                            roleName = "Cashier"
                        });
                });

            modelBuilder.Entity("backend.model.userModel", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("userId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            userId = "c23a5fa3-ba26-480a-b16c-55cab199e275",
                            password = "$2a$11$0mufpUUygE3jSNYUKm4f6uj1m3jI7/RlN0MJirBjzuFxdd6iBjZLK",
                            username = "duc19092005@email.com"
                        });
                });

            modelBuilder.Entity("backend.model.userRoleModel", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("roleId")
                        .HasColumnType("varchar(150)");

                    b.HasKey("userId", "roleId");

                    b.HasIndex("roleId");

                    b.ToTable("userRole");

                    b.HasData(
                        new
                        {
                            userId = "c23a5fa3-ba26-480a-b16c-55cab199e275",
                            roleId = "6ae7fd25-7abc-4886-b3d2-7a6bffbbb62b"
                        },
                        new
                        {
                            userId = "c23a5fa3-ba26-480a-b16c-55cab199e275",
                            roleId = "b6bc151a-b4b4-41d6-bae4-62ce5627be2f"
                        });
                });

            modelBuilder.Entity("DataAccess.model.customerModel", b =>
                {
                    b.HasOne("backend.model.userModel", "userModel")
                        .WithOne("customerModel")
                        .HasForeignKey("DataAccess.model.customerModel", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userModel");
                });

            modelBuilder.Entity("backend.model.userRoleModel", b =>
                {
                    b.HasOne("backend.model.roleModel", "roleModel")
                        .WithMany("userRoleModel")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.model.userModel", "userModel")
                        .WithMany("userRoleModel")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("roleModel");

                    b.Navigation("userModel");
                });

            modelBuilder.Entity("backend.model.roleModel", b =>
                {
                    b.Navigation("userRoleModel");
                });

            modelBuilder.Entity("backend.model.userModel", b =>
                {
                    b.Navigation("customerModel")
                        .IsRequired();

                    b.Navigation("userRoleModel");
                });
#pragma warning restore 612, 618
        }
    }
}
