// <auto-generated />
using DataAccess.dbConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(threaterManagementDbContext))]
    [Migration("20250924023049_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.model.customerModel", b =>
                {
                    b.Property<string>("customerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("customerIdentityNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("customerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("customerId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("DataAccess.model.roleModel", b =>
                {
                    b.Property<string>("roleId")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("roleName")
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("roleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            roleId = "a1b2c3d4-e5f6-7890-1234-567890abcdef",
                            roleName = "Director"
                        },
                        new
                        {
                            roleId = "b1c2d3e4-f5a6-8901-2345-67890abcdef1",
                            roleName = "Customer"
                        },
                        new
                        {
                            roleId = "d1e2f3g4-h5i6-0123-4567-890abcdef123",
                            roleName = "Threater Manager"
                        },
                        new
                        {
                            roleId = "e1f2g3h4-i5j6-1234-5678-90abcdef1234",
                            roleName = "System Manager"
                        },
                        new
                        {
                            roleId = "f1g2h3i4-j5k6-2345-6789-0abcdef12345",
                            roleName = "Movie Manager"
                        },
                        new
                        {
                            roleId = "c1d2e3f4-g5h6-9012-3456-7890abcdef12",
                            roleName = "Cashier"
                        });
                });

            modelBuilder.Entity("DataAccess.model.userModel", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("userId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            userId = "00a1b2c3-d4e5-f678-90ab-cdef01234567",
                            password = "$2a$12$PFeVPgS2ffEm1oY6OqldHutsGi0IJnMu3HCc6EUTS1RB32/cZNILy",
                            username = "duc19092005@email.com"
                        });
                });

            modelBuilder.Entity("DataAccess.model.userRoleModel", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("roleId")
                        .HasColumnType("varchar(150)");

                    b.HasKey("userId", "roleId");

                    b.HasIndex("roleId");

                    b.ToTable("userRole");

                    b.HasData(
                        new
                        {
                            userId = "00a1b2c3-d4e5-f678-90ab-cdef01234567",
                            roleId = "a1b2c3d4-e5f6-7890-1234-567890abcdef"
                        },
                        new
                        {
                            userId = "00a1b2c3-d4e5-f678-90ab-cdef01234567",
                            roleId = "b1c2d3e4-f5a6-8901-2345-67890abcdef1"
                        });
                });

            modelBuilder.Entity("DataAccess.model.customerModel", b =>
                {
                    b.HasOne("DataAccess.model.userModel", "userModel")
                        .WithOne("customerModel")
                        .HasForeignKey("DataAccess.model.customerModel", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userModel");
                });

            modelBuilder.Entity("DataAccess.model.userRoleModel", b =>
                {
                    b.HasOne("DataAccess.model.roleModel", "roleModel")
                        .WithMany("userRoleModel")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.model.userModel", "userModel")
                        .WithMany("userRoleModel")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("roleModel");

                    b.Navigation("userModel");
                });

            modelBuilder.Entity("DataAccess.model.roleModel", b =>
                {
                    b.Navigation("userRoleModel");
                });

            modelBuilder.Entity("DataAccess.model.userModel", b =>
                {
                    b.Navigation("customerModel")
                        .IsRequired();

                    b.Navigation("userRoleModel");
                });
#pragma warning restore 612, 618
        }
    }
}
