// <auto-generated />
using System;
using DataAccess.dbConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(threaterManagementDbContext))]
    [Migration("20251001091530_add-product-table")]
    partial class addproducttable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.model.Cinema", b =>
                {
                    b.Property<string>("cinemaId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("cinemaAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cinemaHotLineNumber")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("cinemaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cinemaStatus")
                        .HasColumnType("int");

                    b.HasKey("cinemaId");

                    b.ToTable("Cinemas");
                });

            modelBuilder.Entity("DataAccess.model.Genre", b =>
                {
                    b.Property<string>("movieGenreId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("movieGenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("movieGenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("DataAccess.model.cinemaProductModel", b =>
                {
                    b.Property<string>("cinemaId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("productId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("productAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cinemaId", "productId");

                    b.HasIndex("productId");

                    b.ToTable("cinemaProductModel");
                });

            modelBuilder.Entity("DataAccess.model.cinemaRoomModel", b =>
                {
                    b.Property<string>("cinemaRoomId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("cinemaId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("cinemaRoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("visualFormatId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("cinemaRoomId");

                    b.HasIndex("cinemaId");

                    b.HasIndex("visualFormatId");

                    b.ToTable("CinemaRooms");
                });

            modelBuilder.Entity("DataAccess.model.customerModel", b =>
                {
                    b.Property<string>("customerId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("customerIdentityNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("customerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("customerId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("DataAccess.model.discountModel", b =>
                {
                    b.Property<string>("roleId")
                        .HasColumnType("varchar(100)");

                    b.Property<double>("discountNumber")
                        .HasColumnType("float");

                    b.Property<string>("roleModelroleId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("roleId");

                    b.HasIndex("roleId")
                        .IsUnique();

                    b.HasIndex("roleModelroleId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("DataAccess.model.foodOrderDetail", b =>
                {
                    b.Property<string>("orderId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("foodInformationId")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PriceEach")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("quanlity")
                        .HasColumnType("int");

                    b.HasKey("orderId", "foodInformationId");

                    b.HasIndex("foodInformationId");

                    b.ToTable("FoodOrderDetails");
                });

            modelBuilder.Entity("DataAccess.model.movieComment", b =>
                {
                    b.Property<string>("commentId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("commentContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movieId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("commentId");

                    b.HasIndex("movieId");

                    b.HasIndex("userId");

                    b.ToTable("MovieComments");
                });

            modelBuilder.Entity("DataAccess.model.movieGenre", b =>
                {
                    b.Property<string>("movieId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("genereId")
                        .HasColumnType("varchar(100)");

                    b.HasKey("movieId", "genereId");

                    b.HasIndex("genereId");

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("DataAccess.model.movieInformation", b =>
                {
                    b.Property<string>("movieId")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("endedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.Property<int>("miniAge")
                        .HasColumnType("int");

                    b.Property<string>("movieActor")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("movieDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movieDirector")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("movieDuration")
                        .HasColumnType("int");

                    b.Property<string>("movieImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movieLanguage")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("movieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("movieTrailerUrl")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("releaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("movieId");

                    b.ToTable("MovieInformation");
                });

            modelBuilder.Entity("DataAccess.model.movieSchedule", b =>
                {
                    b.Property<string>("movieScheduleId")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("cinemaRoomId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("dayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("hourSchedule")
                        .HasColumnType("int");

                    b.Property<string>("movieId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("visualFormatId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("movieScheduleId");

                    b.HasIndex("cinemaRoomId");

                    b.HasIndex("movieId");

                    b.HasIndex("visualFormatId");

                    b.ToTable("MovieSchedules");
                });

            modelBuilder.Entity("DataAccess.model.movieVisualFormat", b =>
                {
                    b.Property<string>("movieId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("visualFormatId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("priceForVisualFormatpriceId")
                        .HasColumnType("varchar(100)");

                    b.HasKey("movieId", "visualFormatId");

                    b.HasIndex("priceForVisualFormatpriceId");

                    b.HasIndex("visualFormatId");

                    b.ToTable("MovieVisualFormats");
                });

            modelBuilder.Entity("DataAccess.model.orderModel", b =>
                {
                    b.Property<string>("orderId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerID")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("paymentRequestCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("totalAmount")
                        .HasColumnType("bigint");

                    b.HasKey("orderId");

                    b.HasIndex("customerID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DataAccess.model.priceForVisualFormat", b =>
                {
                    b.Property<string>("priceId")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("priceDetail")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("visualFormatId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("priceId");

                    b.ToTable("PriceForVisualFormats");
                });

            modelBuilder.Entity("DataAccess.model.productModel", b =>
                {
                    b.Property<string>("productId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("productDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productImage")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("productPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("productId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DataAccess.model.roleModel", b =>
                {
                    b.Property<string>("roleId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("roleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            roleId = "a1b2c3d4-e5f6-7890-1234-567890abcdef",
                            roleName = "Director"
                        },
                        new
                        {
                            roleId = "b1c2d3e4-f5a6-8901-2345-67890abcdef1",
                            roleName = "Customer"
                        },
                        new
                        {
                            roleId = "d1e2f3g4-h5i6-0123-4567-890abcdef123",
                            roleName = "Threater Manager"
                        },
                        new
                        {
                            roleId = "e1f2g3h4-i5j6-1234-5678-90abcdef1234",
                            roleName = "System Manager"
                        },
                        new
                        {
                            roleId = "f1g2h3i4-j5k6-2345-6789-0abcdef12345",
                            roleName = "Movie Manager"
                        },
                        new
                        {
                            roleId = "c1d2e3f4-g5h6-9012-3456-7890abcdef12",
                            roleName = "Cashier"
                        });
                });

            modelBuilder.Entity("DataAccess.model.seatsModel", b =>
                {
                    b.Property<string>("seatsId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("cinemaRommId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("seatsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("seatsStatus")
                        .HasColumnType("int");

                    b.HasKey("seatsId");

                    b.HasIndex("cinemaRommId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("DataAccess.model.staffModel", b =>
                {
                    b.Property<string>("staffId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("cinemaId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("staffIdentityCode")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("staffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("staffId");

                    b.HasIndex("cinemaId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("DataAccess.model.ticketOrderDetail", b =>
                {
                    b.Property<string>("orderId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("seatId")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PriceEach")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("movieScheduleID")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("orderId", "seatId");

                    b.HasIndex("movieScheduleID");

                    b.HasIndex("seatId");

                    b.ToTable("TicketOrderDetails");
                });

            modelBuilder.Entity("DataAccess.model.typeofUserDiscountModel", b =>
                {
                    b.Property<string>("typeofUserDiscountId")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("discountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("typeOfUser")
                        .HasColumnType("int");

                    b.HasKey("typeofUserDiscountId");

                    b.ToTable("TypeOfUserDiscounts");
                });

            modelBuilder.Entity("DataAccess.model.userModel", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("discountModelroleId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("userId");

                    b.HasIndex("discountModelroleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            userId = "00a1b2c3-d4e5-f678-90ab-cdef01234567",
                            password = "$2a$12$PFeVPgS2ffEm1oY6OqldHutsGi0IJnMu3HCc6EUTS1RB32/cZNILy",
                            username = "duc19092005@email.com"
                        });
                });

            modelBuilder.Entity("DataAccess.model.userRoleModel", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("roleId")
                        .HasColumnType("varchar(100)");

                    b.HasKey("userId", "roleId");

                    b.HasIndex("roleId");

                    b.ToTable("userRole");

                    b.HasData(
                        new
                        {
                            userId = "00a1b2c3-d4e5-f678-90ab-cdef01234567",
                            roleId = "a1b2c3d4-e5f6-7890-1234-567890abcdef"
                        },
                        new
                        {
                            userId = "00a1b2c3-d4e5-f678-90ab-cdef01234567",
                            roleId = "b1c2d3e4-f5a6-8901-2345-67890abcdef1"
                        });
                });

            modelBuilder.Entity("DataAccess.model.visualFormat", b =>
                {
                    b.Property<string>("visualFormatId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("priceId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("visualFormatName")
                        .IsRequired()
                        .HasColumnType("char(20)");

                    b.HasKey("visualFormatId");

                    b.HasIndex("priceId");

                    b.HasIndex("visualFormatName")
                        .IsUnique();

                    b.ToTable("VisualFormats");
                });

            modelBuilder.Entity("DataAccess.model.cinemaProductModel", b =>
                {
                    b.HasOne("DataAccess.model.productModel", "productModel")
                        .WithMany("cinemaProductModel")
                        .HasForeignKey("cinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.model.Cinema", "Cinema")
                        .WithMany("cinemaProductModel")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("productModel");
                });

            modelBuilder.Entity("DataAccess.model.cinemaRoomModel", b =>
                {
                    b.HasOne("DataAccess.model.Cinema", "Cinema")
                        .WithMany("cinemaRoomModel")
                        .HasForeignKey("cinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.model.visualFormat", "visualFormat")
                        .WithMany()
                        .HasForeignKey("visualFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("visualFormat");
                });

            modelBuilder.Entity("DataAccess.model.customerModel", b =>
                {
                    b.HasOne("DataAccess.model.userModel", "userModel")
                        .WithOne("customerModel")
                        .HasForeignKey("DataAccess.model.customerModel", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userModel");
                });

            modelBuilder.Entity("DataAccess.model.discountModel", b =>
                {
                    b.HasOne("DataAccess.model.roleModel", "roleModel")
                        .WithMany()
                        .HasForeignKey("roleModelroleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("roleModel");
                });

            modelBuilder.Entity("DataAccess.model.foodOrderDetail", b =>
                {
                    b.HasOne("DataAccess.model.productModel", "productModel")
                        .WithMany()
                        .HasForeignKey("foodInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.model.orderModel", "orderModel")
                        .WithMany("foodOrderDetail")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("orderModel");

                    b.Navigation("productModel");
                });

            modelBuilder.Entity("DataAccess.model.movieComment", b =>
                {
                    b.HasOne("DataAccess.model.movieInformation", "movieInformation")
                        .WithMany("movieComment")
                        .HasForeignKey("movieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.model.userModel", "userModel")
                        .WithMany("movieComment")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("movieInformation");

                    b.Navigation("userModel");
                });

            modelBuilder.Entity("DataAccess.model.movieGenre", b =>
                {
                    b.HasOne("DataAccess.model.Genre", "Genre")
                        .WithMany("movieGenre")
                        .HasForeignKey("genereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.model.movieInformation", "movieInformation")
                        .WithMany("movieGenreInformation")
                        .HasForeignKey("movieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("movieInformation");
                });

            modelBuilder.Entity("DataAccess.model.movieSchedule", b =>
                {
                    b.HasOne("DataAccess.model.cinemaRoomModel", "cinemaRoomModel")
                        .WithMany()
                        .HasForeignKey("cinemaRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.model.movieInformation", "movieInformation")
                        .WithMany("movieSchedule")
                        .HasForeignKey("movieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.model.visualFormat", "visualFormat")
                        .WithMany()
                        .HasForeignKey("visualFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cinemaRoomModel");

                    b.Navigation("movieInformation");

                    b.Navigation("visualFormat");
                });

            modelBuilder.Entity("DataAccess.model.movieVisualFormat", b =>
                {
                    b.HasOne("DataAccess.model.movieInformation", "movieInformation")
                        .WithMany()
                        .HasForeignKey("movieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.model.priceForVisualFormat", null)
                        .WithMany("movieVisualFormat")
                        .HasForeignKey("priceForVisualFormatpriceId");

                    b.HasOne("DataAccess.model.visualFormat", "visualFormat")
                        .WithMany()
                        .HasForeignKey("visualFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("movieInformation");

                    b.Navigation("visualFormat");
                });

            modelBuilder.Entity("DataAccess.model.orderModel", b =>
                {
                    b.HasOne("DataAccess.model.userModel", "userModel")
                        .WithMany()
                        .HasForeignKey("customerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userModel");
                });

            modelBuilder.Entity("DataAccess.model.seatsModel", b =>
                {
                    b.HasOne("DataAccess.model.cinemaRoomModel", "cinemaRoomModel")
                        .WithMany("seatsModel")
                        .HasForeignKey("cinemaRommId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cinemaRoomModel");
                });

            modelBuilder.Entity("DataAccess.model.staffModel", b =>
                {
                    b.HasOne("DataAccess.model.Cinema", "Cinema")
                        .WithMany("staffModel")
                        .HasForeignKey("cinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("DataAccess.model.ticketOrderDetail", b =>
                {
                    b.HasOne("DataAccess.model.movieSchedule", "movieSchedule")
                        .WithMany("ticketOrderDetail")
                        .HasForeignKey("movieScheduleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.model.orderModel", "orderModel")
                        .WithMany()
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.model.seatsModel", "seatsModel")
                        .WithMany()
                        .HasForeignKey("seatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("movieSchedule");

                    b.Navigation("orderModel");

                    b.Navigation("seatsModel");
                });

            modelBuilder.Entity("DataAccess.model.userModel", b =>
                {
                    b.HasOne("DataAccess.model.discountModel", "discountModel")
                        .WithMany()
                        .HasForeignKey("discountModelroleId");

                    b.Navigation("discountModel");
                });

            modelBuilder.Entity("DataAccess.model.userRoleModel", b =>
                {
                    b.HasOne("DataAccess.model.roleModel", "roleModel")
                        .WithMany("userRoleModel")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.model.userModel", "userModel")
                        .WithMany("userRoleModel")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("roleModel");

                    b.Navigation("userModel");
                });

            modelBuilder.Entity("DataAccess.model.visualFormat", b =>
                {
                    b.HasOne("DataAccess.model.priceForVisualFormat", "priceForVisualFormat")
                        .WithMany()
                        .HasForeignKey("priceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("priceForVisualFormat");
                });

            modelBuilder.Entity("DataAccess.model.Cinema", b =>
                {
                    b.Navigation("cinemaProductModel");

                    b.Navigation("cinemaRoomModel");

                    b.Navigation("staffModel");
                });

            modelBuilder.Entity("DataAccess.model.Genre", b =>
                {
                    b.Navigation("movieGenre");
                });

            modelBuilder.Entity("DataAccess.model.cinemaRoomModel", b =>
                {
                    b.Navigation("seatsModel");
                });

            modelBuilder.Entity("DataAccess.model.movieInformation", b =>
                {
                    b.Navigation("movieComment");

                    b.Navigation("movieGenreInformation");

                    b.Navigation("movieSchedule");
                });

            modelBuilder.Entity("DataAccess.model.movieSchedule", b =>
                {
                    b.Navigation("ticketOrderDetail");
                });

            modelBuilder.Entity("DataAccess.model.orderModel", b =>
                {
                    b.Navigation("foodOrderDetail");
                });

            modelBuilder.Entity("DataAccess.model.priceForVisualFormat", b =>
                {
                    b.Navigation("movieVisualFormat");
                });

            modelBuilder.Entity("DataAccess.model.productModel", b =>
                {
                    b.Navigation("cinemaProductModel");
                });

            modelBuilder.Entity("DataAccess.model.roleModel", b =>
                {
                    b.Navigation("userRoleModel");
                });

            modelBuilder.Entity("DataAccess.model.userModel", b =>
                {
                    b.Navigation("customerModel")
                        .IsRequired();

                    b.Navigation("movieComment");

                    b.Navigation("userRoleModel");
                });
#pragma warning restore 612, 618
        }
    }
}
