// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.dbConnection;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(threaterManagementDbContext))]
    partial class threaterManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.model.roleModel", b =>
                {
                    b.Property<string>("roleId")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("roleName")
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("roleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            roleId = "6a0576ad-603c-45b2-9171-cf151102ab8d",
                            roleName = "Director"
                        },
                        new
                        {
                            roleId = "2adfc60f-6e26-4785-9b79-09f0f1ae2c90",
                            roleName = "Customer"
                        },
                        new
                        {
                            roleId = "620d4cc7-0ade-4925-abea-ebf0e3b342fe",
                            roleName = "Threater Manager"
                        },
                        new
                        {
                            roleId = "deb8c642-51df-4ef1-a792-7a4495376e18",
                            roleName = "System Manager"
                        },
                        new
                        {
                            roleId = "13b03e6c-a8d2-4165-9634-508090051e7d",
                            roleName = "Movie Manager"
                        },
                        new
                        {
                            roleId = "c1ad8e30-7533-47b4-9549-f078801b8a4d",
                            roleName = "Cashier"
                        });
                });

            modelBuilder.Entity("backend.model.userModel", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("userId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            userId = "15d4096c-5e1f-41b1-8cbc-599c890f711a",
                            password = "$2a$10$MxznQNLgmO.zFyQcaqpEFe9xSyTP2EO1s4IoFKInNmhL.F8XJwakC",
                            username = "duc19092005@email.com"
                        });
                });

            modelBuilder.Entity("backend.model.userRoleModel", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("roleId")
                        .HasColumnType("varchar(150)");

                    b.HasKey("userId", "roleId");

                    b.HasIndex("roleId");

                    b.ToTable("userRole");

                    b.HasData(
                        new
                        {
                            userId = "15d4096c-5e1f-41b1-8cbc-599c890f711a",
                            roleId = "6a0576ad-603c-45b2-9171-cf151102ab8d"
                        },
                        new
                        {
                            userId = "15d4096c-5e1f-41b1-8cbc-599c890f711a",
                            roleId = "2adfc60f-6e26-4785-9b79-09f0f1ae2c90"
                        });
                });

            modelBuilder.Entity("backend.model.userRoleModel", b =>
                {
                    b.HasOne("backend.model.roleModel", "roleModel")
                        .WithMany("userRoleModel")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.model.userModel", "userModel")
                        .WithMany("userRoleModel")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("roleModel");

                    b.Navigation("userModel");
                });

            modelBuilder.Entity("backend.model.roleModel", b =>
                {
                    b.Navigation("userRoleModel");
                });

            modelBuilder.Entity("backend.model.userModel", b =>
                {
                    b.Navigation("userRoleModel");
                });
#pragma warning restore 612, 618
        }
    }
}
